name: Update Social Preview

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  update-social-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print repository metadata
        run: |
          echo "Repository name: $GITHUB_REPOSITORY"
          echo "Repository owner: $GITHUB_REPOSITORY_OWNER"
      - name: Check if image exists
        run: |
          if [ ! -f "./public/images/default-hero.jpg" ]; then
            echo "❌ Error: Image file not found at ./public/images/default-hero.jpg"
            exit 1
          fi
          echo "✅ Image file found"
          ls -l "./public/images/default-hero.jpg"
      - name: Upload social preview image
        run: |
          echo "Updating repository settings..."
          RESPONSE=$(curl -w "\n%{http_code}" \
            -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ github.repository }} \
            -d "{\"name\":\"${{ github.event.repository.name }}\",\"default_branch\":\"main\",\"private\":false}")
          
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "❌ Error updating repository settings. Status: $HTTP_STATUS"
            echo "$RESPONSE" | head -n-1